apiVersion: v1
kind: Service
metadata:
  name: retail-app-preview-service
  namespace: {{ .Values.namespace }}
spec:
  selector:
    app: retail

  ports:
    - port: {{ .Values.retailApp.service.port }}
      targetPort: {{ .Values.retailApp.service.targetPort }}

  type: ClusterIP