apiVersion: v1
kind: Secret
metadata:
  name: retail-app-secret
  namespace: {{ .Values.namespace }}
type: Opaque
data:
  EMAIL_USER: {{ .Values.retailApp.secret.emailUser | b64enc }}
  EMAIL_PASS: {{ .Values.retailApp.secret.emailPass | b64enc }}